### ISSUE TITLE
Broken link in `README.md`

### ISSUE THREAD

**Issue by streetCoderr** [geocaml/ocaml-geojson#12]
## Description

The link given on jsonm in [README.md](https://github.com/geocaml/ocaml-geojson/blob/main/README.md) appears to be broken

![Screenshot (14)](https://user-images.githubusercontent.com/98380817/160374364-dd8b7457-c4a0-48e3-8c81-edbccb181a9c.png)

**Comment by patricoferris** [comment]
Thanks, fixed in #19
