### ISSUE TITLE
Add bounding box field

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-geojson#13]
GeoJSON objects can contain a `bbox` (bounding box) field which has been overlooked in the current implementation. This is specified in the RFC here: https://datatracker.ietf.org/doc/html/rfc7946#section-5

We should add this to the GeoJSON objects with the type probably being something like `float array option`. So all of the objects will have a new function:

```ocaml
val bbox : t -> float array option
```

**Comment by streetCoderr** [comment]
I would love to give this a try.
Please can you assign the task to me?

**Comment by imajinarts** [comment]
Hi @patricoferris I will like to work on this project if you'll assign me to it

**Comment by imajinarts** [comment]
> I would love to give this a try.
> Please can you assign the task to me?
> 

Would you like to Collab 😁

**Comment by streetCoderr** [comment]
> > I would love to give this a try.
> > Please can you assign the task to me?
> 
> Would you like to Collab 😁

Thank you @imajinarts, but I think I'm almost done with it.

**Comment by patricoferris** [comment]
Fixed in #20
