### ISSUE TITLE
Add `id` field to Feature Objects

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-geojson#21]
From the [RFC](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) we have that:

> If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.

For example:

```
{
       "type": "Feature",
       "id": "f1",
       "geometry": {...},
       "properties": {...}
}
```

And currently we would just drop this field entirely: 

https://github.com/geocaml/ocaml-geojson/blob/9eaaa54fa433bf732069e3e4623f9fd29c38b754/src/geojson/geojson.ml#L268

This is somewhat relevant to #20 as both will probably end up changing the type of `Feature.t` so there may be a bit of massaging needed for the PR to fix this, but that's okay.

**Comment by imajinarts** [comment]
@patricoferris I would love to give this a shot... Please assign it to me....

**Comment by imajinarts** [comment]
Hi @patricoferris is the value of the id going to come from the Json section or a randomly generated number?

**Comment by patricoferris** [comment]
The `id` field will be parsed from the JSON if it exists :))

**Comment by streetCoderr** [comment]
Hi @imajinarts, I just worked on a similar issue.
If you are having problems, please don't hesitate to reach out to me.
I want to see you make your first PR 😊
You've got this 💪💪

**Comment by imajinarts** [comment]
@streetCoderr I'll really appreciate the explanation.... Hopefully it'll tie with what I already have and I'll soon open the PR

**Comment by Techbae22** [comment]
Hello @streetCoderr and @imajinarts @patricoferris ,

I could use some help here. Do I need to have a contributing project assigned to me or I can take up any project to contribute to?  

Thanks

**Comment by streetCoderr** [comment]
> @streetCoderr I'll really appreciate the explanation.... Hopefully it'll tie with what I already have and I'll soon open the PR

Alright @imajinarts. Well done.

**Comment by streetCoderr** [comment]
> Hello @streetCoderr and @imajinarts @patricoferris ,
> 
> I could use some help here. Do I need to have a contributing project assigned to me or I can take up any project to contribute to?
> 
> Thanks

Hi @Techbae22
If you see any issue that no one is working on, you can ask our mentor @patricoferris  to assign the task to you.
He will attend to you when he comes online

**Comment by imajinarts** [comment]
@Techbae22 thanks and put mentor @patricoferris has the right to decide meanwhile feel free to throw in light on any issue... It is indeed open source and so collaboration is better

**Comment by Techbae22** [comment]
Thanks everyone
