### ISSUE TITLE
Installing correct version of `ocamlformat`

### ISSUE THREAD

**Issue by IIITM-Jay** [geocaml/ocaml-geojson#22]
By default when installing the `ocamlformat` via the command `opam install ocamlformat` it automatically  installs the latest version of it as `0.21.0` but as per the `.ocamlformat` file we require `0.20.1`. 

![image](https://user-images.githubusercontent.com/65283880/161386694-dba10b95-90e7-4f3e-a7f5-171a3960ce41.png)

**Comment by IIITM-Jay** [comment]
Hi Sir @patricoferris , I solved this issue by using the command `opam install ocamlformat=0.20.1` , but sir I have a doubt that as why we are not using the latest version of `ocamlformat` (any stability issue with `0.21.0`), just to know more about ocaml and opam and to gain more knowledge on that. 

**(way-1)** And if we have to install mentioned `0.20.1` version only , then I think it will be good if we add the command `opam install ocamlformat=0.20.1` in the `CONTRIBUTING.md` file in order to make it ease for the new contributors as this is the common command `opam install ocamlformat` as mentioned on the [git hub page of ocamlformat](https://github.com/ocaml-ppx/ocamlformat) but this installs the latest version

**(way-2)** or else, if we want to work on latest version of it, we have to change the `version` inside `.ocamlformat` file. 

If you don't mind, shall I make a pull request on this with whichever way you like _(either way-1 or 2)_.

**Comment by IIITM-Jay** [comment]
Hi Sir @patricoferris , Good Afternoon,
any guidance on above...

**Comment by patricoferris** [comment]
Hi @IIITM-Jay,

Thanks :))  Yeah OCaml (opam) still have no good way to track dev dependencies -- I think just mentioning a user can get the correct version of OCamlformat from the `.ocamlformat` file is enough (no need to mention the version otherwise we will have to keep changing it in two places).

Deciding on what OCamlformat to use can be tricky -- using the latest means the user must be aware that they probably need to do an `opam update` to ensure their repository has the latest OCamlforrmat information. So it is a trade-off. If you want to also bump it to `0.21.0` at the same time I don't mind ^^

**Comment by IIITM-Jay** [comment]
Hi @patricoferris , Thank you so much for letting me know about this. Got clear with whatever you have explained above.
Closing now as it's no longer needed

**Comment by patricoferris** [comment]
Hi @IIITM-Jay, sorry there's been some confusion :)) 

What I was trying to say was, I think adding something to the `CONTRIBUTING/md` would be a good thing, it should just tell people to `opam install ocamlformat=X.XX.X` for whatever `X.XX.X` is in the `.ocamlformat` file. Does that make sense?

**Comment by IIITM-Jay** [comment]
Hi Patrick Sir, @patricoferris , Thank you so much for reopening this. Actually yes, that was the only main motive to open this issue (and what I was also trying to say by opening this),   what you have have said above also is so true.

Thank you once again for considering this and soon I will create a PR regarding this.

Thanking You.
-Jay

**Comment by IIITM-Jay** [comment]
Hi Sir, @patricoferris , I have created a PR for this.

**Comment by patricoferris** [comment]
Fixed in #24
