### ISSUE TITLE
Add test for Feature and Feature Collection

### ISSUE THREAD

**Issue by streetCoderr** [geocaml/ocaml-geojson#29]
Add validity checks for the remaining 2 GeoJSON types: Feature and FeatureCollection

**Comment by streetCoderr** [comment]
Hi @patricoferris, please I would love to work on this issue when you merge my PR

**Comment by patricoferris** [comment]
Thanks, I've assigned you ^^

**Comment by streetCoderr** [comment]
> Thanks, I've assigned you ^^

Hi @patricoferris. 
Good morning and thank you too.😊😊


Sir, I want to start working on this, but the API was changed in the issue I last worked on which is yet to be merged.
The tests I will write will depend on the new API; so I was thinking I would have to wait for you to merge the pull request so that I could branch off **main**.
Or is there a way I could continue with this without having to wait for the PR in concern to be merged

**Comment by patricoferris** [comment]
Yep, all merged now. 

> I was thinking of branching off the branch I pushed to the concerned PR, but I doubt that it is a good idea.

That's actually perfectly fine and lots of people do that in practice as it tends to be very easy to rebase once the PR is merged. You can keep rebasing on top of the unmerged branch if that is still being worked on too. If you open a PR with those unmerged commits then usually just adding a comment to indicate that that is the case is good practice :))

**Comment by streetCoderr** [comment]
> Yep, all merged now.
> 
> > I was thinking of branching off the branch I pushed to the concerned PR, but I doubt that it is a good idea.
> 
> That's actually perfectly fine and lots of people do that in practice as it tends to be very easy to rebase once the PR is merged. You can keep rebasing on top of the unmerged branch if that is still being worked on too. If you open a PR with those unmerged commits then usually just adding a comment to indicate that that is the case is good practice :))

Okay Sir😊.
I'm getting better at git/github, thanks to you.
Thank you so much for this enlightenment. I really appreciate.

**Comment by patricoferris** [comment]
Thanks! Fixed in #31
