### ISSUE TITLE
Add tests for 3d

### ISSUE THREAD

**Issue by streetCoderr** [geocaml/ocaml-geojson#33]
We have tested for Geometry, Feature and FeatureCollection; we have also tested for when they include bbox; but in all these, we have only taken 2d into consideration.
Knowing that a position can be represented in 3 dimensions, lets add tests to account for 3d.

**Comment by streetCoderr** [comment]
Hi Sir @patricoferris, I would like to work on this Sir
Please can you assign it to me.
Thank you as I await your response

**Comment by patricoferris** [comment]
Sounds like a great idea to me, thanks :))

**Comment by streetCoderr** [comment]
Thank you so much Sir

**Comment by streetCoderr** [comment]
Sir I would love to hear your thoughts on this issue.

I was thinking 2 tests would suffice for this.

## Test 1
My initial thought was that since we have written 2d tests for the GeoJson types, we are already confident that all is working as expected. What we are not sure of yet, is if it would still behave as expected if we are dealing with 3d positions.
So I was thinking we can pick up just one of the GeoJSON types, and test for 3d and that would cover up for the rest.
For instance, because FeatureCollection embodies Feature, and Feature in turn, embodies Geometry. We could just test for 3d on only FeatureCollection and then draw conclusion for Feature and Geometry from there.

## Test 2
For the second test, we test reading bbox from 3d provided positions on any chosen GeoJSON type.

What do you think Sir. Is this okay?
Or should I test for 3d on all GeoJSON types?

Thank you Sir, as I await response.

**Comment by streetCoderr** [comment]
> 

I think I would rather test on the GeoJSON types.
I don't want to assume anything. Leaving no stones unturned.
Is this okay by you Sir?

**Comment by patricoferris** [comment]
Hey, sorry for the slow response.

> I think I would rather test on all the GeoJSON types.

I don't think we need to do that. The coordinate system, whether 2D or 3D, is confined to the Point/Position geometry type which the others are based off. I think going for "Test 1" for now will be sufficient and we can incrementally add more if we find holes in the tests:)) 

Thanks for the diligent work ^^

**Comment by streetCoderr** [comment]
> Hey, sorry for the slow response.
> 
> > I think I would rather test on all the GeoJSON types.
> 
> I don't think we need to do that. The coordinate system, whether 2D or 3D, is confined to the Point/Position geometry type which the others are based off. I think going for "Test 1" for now will be sufficient and we can incrementally add more if we find holes in the tests:))
> 
> Thanks for the diligent work ^^

I thought as much Sir. I was just not sure.
Thank you for clearing my doubts.
I will proceed with a PR now😊😊

> Thanks for the diligent work ^^

I appreciate this. Thanks a lot

**Comment by patricoferris** [comment]
Fixed in #36. Thanks!
