### ISSUE TITLE
Add ring function to Polygon's API

### ISSUE THREAD

**Issue by streetCoderr** [geocaml/ocaml-geojson#37]
While trying to solve #33, I attempted to write 3d tests for all GeoJson types before @patricoferris made me understand it was not really necessary. Therefore, I deleted the redundancies and worked on only what was necessary.

However, my redundant attempt opened up a new issue. 
While writing 3d tests for all the GeoJSON types, Polygon posed a problem. The reason was that there was no function provided in the API with which I could get all the linear rings that makes up a polygon. The provided functions either provided only the interior ring or exterior rings, but not both at once.

For context; MultiLineString provided the `lines` function in its API for accessing its lines; MultiPoint and LineString provided the `coordinates` function in it's API for accessing its coordinates; Polygon provides no such thing.

I suggest we add to the API, a function that returns all the linear rings of a Polygon(both interior and exterior). This will come in handy when writing tests for Polygon and MultiPolygon amongst other scenarios.

**Comment by streetCoderr** [comment]
Hi Sir, @patricoferris, please may I have your consent to go ahead with this issue?
Thanks as I await your response

**Comment by patricoferris** [comment]
Seems useful to me!

**Comment by Bash-dot** [comment]
> Hi Sir, @patricoferris, please may I have your consent to go ahead with this issue?
> 
> Thanks as I await your response

@streetCoderr 

I'd like to assist you to work on this issue if you don't mind that is . 
Or @patricoferris  can I please have an issue assigned to me as a beginner.

**Comment by patricoferris** [comment]
Hi @Bash-dot, thanks for the enthusiasm! Unfortunately, this was fixed in #38. I'll try to think of a suitable issue and tag you in it.
