### ISSUE TITLE
Improve the tests

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-geojson#5]
The library is poorly tested at the moment with only a few examples of JSON parsing, it would be good to increase this by adding more validity checks, see for example:

 - Some tests in the Rust library https://github.com/georust/geojson/tree/master/tests/fixtures/canonical
 - Geometry tests in the go library https://github.com/paulmach/go.geojson/blob/master/geometry_test.go

**Comment by IIITM-Jay** [comment]
Hi Sir,
Myself Jay, remembered from last year I have contributed related to unix commands [pull request](https://github.com/ocaml/v2.ocaml.org/pull/1253) that did the task **_Sorted out the Contributors list alphabetically and Optimize the command to display the same_**, but unfortunately last year my initial application wasn't approved. 
But this time it got approved and I am really excited to work with you this time.

I wanted to work on this ( _or any other which you want me to do_), may I request  you to guide me a little bit on how to proceed as I have learnt Ocaml and already cloned this repo and it's going well.

**Comment by IIITM-Jay** [comment]
Hi @patricoferris sir,
while going through the test code I found that the **_MultiPolygon_** geometry is being tested as 
`{
          properties = Some (`O [ ("name", `String "abcd") ]);
          geometry = MultiPolygon (3, 3);
  };`

but that can also be tested as only `{ properties = None; geometry = MultiPolygon (3, 3) };`
I verified this actually by testing on my PC and it's working fine. May I request you to let me suggest why we are using this instead of what I have tried as the only difference is that **MultiPolygon** requires two arguments to test instead of one. 

and, moreover we can also use 
`        { properties = None; geometry = MultiPoint 2 };`
for testing _**MultiPoint**_ geometry as well

**Comment by IIITM-Jay** [comment]
As it's looking good when we test all the geometries like this :point_down: 
![image](https://user-images.githubusercontent.com/65283880/160365720-9faab83f-451a-4877-8f07-5e47484d35d4.png)

waiting for your valuable suggestions on the same.

**Comment by patricoferris** [comment]
Hi @IIITM-Jay, fantastic news that you have been approved for this round, congratulations!

In GeoJSON, [feature objects can have a properties member](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2). Here we are allowing, for the purposes of generating random GeoJSON objects, the user to provide a value for the properties field. It could be `None` or `Some` JSON value. The `test_random` ensures whatever the random GeoJSON that is produced serialises and deserialises (i.e. `to_json` and `of_json`) to the same value. By also testing the `properties` field (by providing `Some value` instead of `None` for all of them) we ensure that this logic also works. Does that make sense?

**Comment by IIITM-Jay** [comment]
@patricoferris  Thank you so much for your guidance.
So shall it be ok if we will test all the geometries with None values once and a separate function with `Some value`.

**Comment by IIITM-Jay** [comment]
Hi @patricoferris (_must guess a very busy schedule, I can understand_) anything that you want to give as a suggestion on my above comment...
waiting for your reply on this task

**Comment by IIITM-Jay** [comment]
Hi @patricoferris Sir, I have just created a PR.
Waiting for your review and valuable guidance on the same.

**Comment by patricoferris** [comment]
Closing this in favour of opening smaller, more specific issues related to the tests.
