### ISSUE TITLE
Refactor Geojson type checking

### ISSUE THREAD

**Issue by patricoferris** [geocaml/ocaml-geojson#6]
At the start of most Geojson parsing we check the type of the JSON to ensure we are trying to parse the correct type of geometric primitive. For example:

https://github.com/geocaml/ocaml-geojson/blob/5d01e0c771e9b06ec6a86a5e95bdb0d409b12514/src/geojson/geojson.ml#L99

This happens quite a few times and the logic could probably be factored out into a separate function that we can reuse so it is easier to maintain.

**Comment by streetCoderr** [comment]
Hello Sir.
Please can i get a go-ahead to tackle this issue.
I would like to work on this.
Thank you as I anticipate your response

**Comment by patricoferris** [comment]
Hi @streetCoderr :))

Thanks for the interest in working on this project! Please do go ahead with this issue and let me know if you encounter any problems.

**Comment by streetCoderr** [comment]
> 

Thank you so much for offering to help @patricoferris . 
I have been working on it.
I will create a pull request when I'm done.
Thanks once again

**Comment by streetCoderr** [comment]
Hi @patricoferris, I think you might want to close this

**Comment by patricoferris** [comment]
Cheers, fixed in #11
