### ISSUE TITLE
Broken link in `Contributing.md` 

### ISSUE THREAD

**Issue by SHIVANGISINGH1** [geocaml/ocaml-geojson#9]
### Description

Broken link to the documentation given in [Contributing.md](https://github.com/geocaml/ocaml-geojson/blob/main/CONTRIBUTING.md) and is redirecting to 404 

![image](https://user-images.githubusercontent.com/80265624/160268021-b234bae0-5efd-46ae-a93c-3a5e38ae53f6.png)

PS: I would like to work on this issue, give me the correct URL and I'll change the Contributing.md accordingly. 😀

**Comment by patricoferris** [comment]
Thanks @SHIVANGISINGH1 the link should be https://v3.ocaml.org/docs/up-and-running
